spring:
  application:
    name: kioscoLaMadrina
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  
  threads:
    virtual:
      enabled: true

server:
  port: ${PORT:8080}
  error:
    include-message: always

kiosco:
  app:
    jwtSecret: ${JWT_SECRET_KEY}
    jwtExpirationMs: 604800000
